#pragma once

typedef enum
{
	BVC_WAVELET_BIORTHOGONAL_1p1,
	BVC_WAVELET_BIORTHOGONAL_1p3,
	BVC_WAVELET_BIORTHOGONAL_1p5,
	BVC_WAVELET_BIORTHOGONAL_2p2,
	BVC_WAVELET_BIORTHOGONAL_2p4,
	BVC_WAVELET_BIORTHOGONAL_2p6,
	BVC_WAVELET_BIORTHOGONAL_2p8,
	BVC_WAVELET_BIORTHOGONAL_3p1,
	BVC_WAVELET_BIORTHOGONAL_3p3,
	BVC_WAVELET_BIORTHOGONAL_3p5,
	BVC_WAVELET_BIORTHOGONAL_3p7,
	BVC_WAVELET_BIORTHOGONAL_3p9,
	BVC_WAVELET_BIORTHOGONAL_4p4,
	BVC_WAVELET_BIORTHOGONAL_5p5,
	BVC_WAVELET_BIORTHOGONAL_6p8,
} bvc_wavelet_biorthogonal_config;