#pragma once

typedef enum
{
	BVC_WAVELET_DAUBECHIES_1,
	BVC_WAVELET_DAUBECHIES_2,
	BVC_WAVELET_DAUBECHIES_3,
	BVC_WAVELET_DAUBECHIES_4,
	BVC_WAVELET_DAUBECHIES_5,
	BVC_WAVELET_DAUBECHIES_6,
	BVC_WAVELET_DAUBECHIES_7,
	BVC_WAVELET_DAUBECHIES_8,
	BVC_WAVELET_DAUBECHIES_9,
	BVC_WAVELET_DAUBECHIES_10,
	BVC_WAVELET_DAUBECHIES_11,
	BVC_WAVELET_DAUBECHIES_12,
	BVC_WAVELET_DAUBECHIES_13,
	BVC_WAVELET_DAUBECHIES_14,
	BVC_WAVELET_DAUBECHIES_15,
	BVC_WAVELET_DAUBECHIES_16,
	BVC_WAVELET_DAUBECHIES_17,
	BVC_WAVELET_DAUBECHIES_18,
	BVC_WAVELET_DAUBECHIES_19,
	BVC_WAVELET_DAUBECHIES_20
} bvc_wavelet_daubechies_config;