#pragma once

#include <stdint.h>
#include <string>

namespace ovc
{
	typedef enum : uint8_t
	{
		WAVELET_REVERSE_BIORTHOGONAL_1p1,
		WAVELET_REVERSE_BIORTHOGONAL_1p3,
		WAVELET_REVERSE_BIORTHOGONAL_1p5,
		WAVELET_REVERSE_BIORTHOGONAL_2p2,
		WAVELET_REVERSE_BIORTHOGONAL_2p4,
		WAVELET_REVERSE_BIORTHOGONAL_2p6,
		WAVELET_REVERSE_BIORTHOGONAL_2p8,
		WAVELET_REVERSE_BIORTHOGONAL_3p1,
		WAVELET_REVERSE_BIORTHOGONAL_3p3,
		WAVELET_REVERSE_BIORTHOGONAL_3p5,
		WAVELET_REVERSE_BIORTHOGONAL_3p7,
		WAVELET_REVERSE_BIORTHOGONAL_3p9,
		WAVELET_REVERSE_BIORTHOGONAL_4p4,
		WAVELET_REVERSE_BIORTHOGONAL_5p5,
		WAVELET_REVERSE_BIORTHOGONAL_6p8
	} wavelet_reverse_biorthogonal_config;

	inline std::string reverse_biorthogonal_config_to_string(wavelet_reverse_biorthogonal_config in_reverse_biorthogonal_config)
	{
		switch (in_reverse_biorthogonal_config)
		{
			case WAVELET_REVERSE_BIORTHOGONAL_1p1:
				return "WAVELET_REVERSE_BIORTHOGONAL_1p1";
			case WAVELET_REVERSE_BIORTHOGONAL_1p3:
				return "WAVELET_REVERSE_BIORTHOGONAL_1p3";
			case WAVELET_REVERSE_BIORTHOGONAL_1p5:
				return "WAVELET_REVERSE_BIORTHOGONAL_1p5";
			case WAVELET_REVERSE_BIORTHOGONAL_2p2:
				return "WAVELET_REVERSE_BIORTHOGONAL_2p2";
			case WAVELET_REVERSE_BIORTHOGONAL_2p4:
				return "WAVELET_REVERSE_BIORTHOGONAL_2p4";
			case WAVELET_REVERSE_BIORTHOGONAL_2p6:
				return "WAVELET_REVERSE_BIORTHOGONAL_2p6";
			case WAVELET_REVERSE_BIORTHOGONAL_2p8:
				return "WAVELET_REVERSE_BIORTHOGONAL_2p8";
			case WAVELET_REVERSE_BIORTHOGONAL_3p1:
				return "WAVELET_REVERSE_BIORTHOGONAL_3p1";
			case WAVELET_REVERSE_BIORTHOGONAL_3p3:
				return "WAVELET_REVERSE_BIORTHOGONAL_3p3";
			case WAVELET_REVERSE_BIORTHOGONAL_3p5:
				return "WAVELET_REVERSE_BIORTHOGONAL_3p5";
			case WAVELET_REVERSE_BIORTHOGONAL_3p7:
				return "WAVELET_REVERSE_BIORTHOGONAL_3p7";
			case WAVELET_REVERSE_BIORTHOGONAL_3p9:
				return "WAVELET_REVERSE_BIORTHOGONAL_3p9";
			case WAVELET_REVERSE_BIORTHOGONAL_4p4:
				return "WAVELET_REVERSE_BIORTHOGONAL_4p4";
			case WAVELET_REVERSE_BIORTHOGONAL_5p5:
				return "WAVELET_REVERSE_BIORTHOGONAL_5p5";
			case WAVELET_REVERSE_BIORTHOGONAL_6p8:
				return "WAVELET_REVERSE_BIORTHOGONAL_6p8";
			default:
				return "";
		}
	}
} // namespace ovc