#pragma once

typedef enum
{
	BVC_WAVELET_SYMLETS_1,
	BVC_WAVELET_SYMLETS_2,
	BVC_WAVELET_SYMLETS_3,
	BVC_WAVELET_SYMLETS_4,
	BVC_WAVELET_SYMLETS_5,
	BVC_WAVELET_SYMLETS_6,
	BVC_WAVELET_SYMLETS_7,
	BVC_WAVELET_SYMLETS_8,
	BVC_WAVELET_SYMLETS_9,
	BVC_WAVELET_SYMLETS_10,
	BVC_WAVELET_SYMLETS_11,
	BVC_WAVELET_SYMLETS_12,
	BVC_WAVELET_SYMLETS_13,
	BVC_WAVELET_SYMLETS_14,
	BVC_WAVELET_SYMLETS_15,
	BVC_WAVELET_SYMLETS_16,
	BVC_WAVELET_SYMLETS_17,
	BVC_WAVELET_SYMLETS_18,
	BVC_WAVELET_SYMLETS_19,
	BVC_WAVELET_SYMLETS_20
} bvc_wavelet_symlets_config;