#pragma once

#include <stdint.h>

typedef enum : uint8_t
{
	OVC_WAVELET_BIORTHOGONAL_1p1,
	OVC_WAVELET_BIORTHOGONAL_1p3,
	OVC_WAVELET_BIORTHOGONAL_1p5,
	OVC_WAVELET_BIORTHOGONAL_2p2,
	OVC_WAVELET_BIORTHOGONAL_2p4,
	OVC_WAVELET_BIORTHOGONAL_2p6,
	OVC_WAVELET_BIORTHOGONAL_2p8,
	OVC_WAVELET_BIORTHOGONAL_3p1,
	OVC_WAVELET_BIORTHOGONAL_3p3,
	OVC_WAVELET_BIORTHOGONAL_3p5,
	OVC_WAVELET_BIORTHOGONAL_3p7,
	OVC_WAVELET_BIORTHOGONAL_3p9,
	OVC_WAVELET_BIORTHOGONAL_4p4,
	OVC_WAVELET_BIORTHOGONAL_5p5,
	OVC_WAVELET_BIORTHOGONAL_6p8,
} ovc_wavelet_biorthogonal_config;