#pragma once

#include <stdint.h>

typedef enum : uint8_t
{
	OVC_WAVELET_SYMLETS_2,
	OVC_WAVELET_SYMLETS_3,
	OVC_WAVELET_SYMLETS_4,
	OVC_WAVELET_SYMLETS_5,
	OVC_WAVELET_SYMLETS_6,
	OVC_WAVELET_SYMLETS_7,
	OVC_WAVELET_SYMLETS_8,
	OVC_WAVELET_SYMLETS_9,
	OVC_WAVELET_SYMLETS_10,
	OVC_WAVELET_SYMLETS_11,
	OVC_WAVELET_SYMLETS_12,
	OVC_WAVELET_SYMLETS_13,
	OVC_WAVELET_SYMLETS_14,
	OVC_WAVELET_SYMLETS_15,
	OVC_WAVELET_SYMLETS_16,
	OVC_WAVELET_SYMLETS_17,
	OVC_WAVELET_SYMLETS_18,
	OVC_WAVELET_SYMLETS_19,
	OVC_WAVELET_SYMLETS_20
} ovc_wavelet_symlets_config;