#pragma once

typedef enum
{
	OVC_VERBOSITY_SILENT,
	OVC_VERBOSITY_ERROR,
	OVC_VERBOSITY_WARNING,
	OVC_VERBOSITY_INFO,
	OVC_VERBOSITY_NOTICE,
	OVC_VERBOSITY_VERBOSE,
	OVC_VERBOSITY_DETAILS
} ovc_verbosity;