#pragma once

#include <stdint.h>

typedef enum : uint8_t
{
	OVC_WAVELET_DAUBECHIES_1,
	OVC_WAVELET_DAUBECHIES_2,
	OVC_WAVELET_DAUBECHIES_3,
	OVC_WAVELET_DAUBECHIES_4,
	OVC_WAVELET_DAUBECHIES_5,
	OVC_WAVELET_DAUBECHIES_6,
	OVC_WAVELET_DAUBECHIES_7,
	OVC_WAVELET_DAUBECHIES_8,
	OVC_WAVELET_DAUBECHIES_9,
	OVC_WAVELET_DAUBECHIES_10,
	OVC_WAVELET_DAUBECHIES_11,
	OVC_WAVELET_DAUBECHIES_12,
	OVC_WAVELET_DAUBECHIES_13,
	OVC_WAVELET_DAUBECHIES_14,
	OVC_WAVELET_DAUBECHIES_15,
	OVC_WAVELET_DAUBECHIES_16,
	OVC_WAVELET_DAUBECHIES_17,
	OVC_WAVELET_DAUBECHIES_18,
	OVC_WAVELET_DAUBECHIES_19,
	OVC_WAVELET_DAUBECHIES_20
} ovc_wavelet_daubechies_config;